version: '3'
name: 'sockets'

services:
  server:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:4444:4444
    volumes:
      - ../../server:/app
      
  serv-side-client:
    image: node:18-alpine
    working_dir: /app
    restart: unless-stopped
    command: sh -c "npm install && npm run dev"
    ports:
      - 127.0.0.1:3333:3333
    volumes:
      - ../../serv-side-client:/app